### PR TITLE
fix: Normalize paths on Windows.

### LINKED ISSUE #1159: `closure-make-deps` generates incorrect paths on Windows.
### To Reproduce

1. Create working directory (e.g. C:\\work\\test).
2. Change directory (e.g. `cd C:\\work\\test`).
3. Clone closure-library (e.g. `git clone https://github.com/google/closure-library.git`).
4. Change directory (e.g. `cd closure-library`).
5. Install npm package (e.g. `npm install`).

Following the above steps will generate closure/goog/deps.js.

When you open deps.js, it has the following contents. 

```
goog.addDependency('../C:\work\test\closure-library\closure\goog\a11y\aria\announcer.js', ['goog.a11y.aria.Announcer'], ['goog.Disposable', 'goog.Timer', 'goog.a11y.aria', 'goog.a11y.aria.LivePriority', 'goog.a11y.aria.State', 'goog.dom', 'goog.dom.TagName', 'goog.object', 'goog.string'], {'lang': 'es6'});
goog.addDependency('../C:\work\test\closure-library\closure\goog\a11y\aria\aria.js', ['goog.a11y.aria'], ['goog.a11y.aria.Role', 'goog.a11y.aria.State', 'goog.a11y.aria.datatables', 'goog.array', 'goog.asserts', 'goog.dom', 'goog.dom.TagName', 'goog.object', 'goog.string']);
```

### Expected behavior

The following content will be generated.

```
goog.addDependency('a11y/aria/announcer.js', ['goog.a11y.aria.Announcer'], ['goog.Disposable', 'goog.Timer', 'goog.a11y.aria', 'goog.a11y.aria.LivePriority', 'goog.a11y.aria.State', 'goog.dom', 'goog.dom.TagName', 'goog.object', 'goog.string'], {'lang': 'es6'});
goog.addDependency('a11y/aria/aria.js', ['goog.a11y.aria'], ['goog.a11y.aria.Role', 'goog.a11y.aria.State', 'goog.a11y.aria.datatables', 'goog.array', 'goog.asserts', 'goog.dom', 'goog.dom.TagName', 'goog.object', 'goog.string']);
```

### Additional context

In "depswriter.py", the path is normalized by the following code.

https://github.com/google/closure-library/blob/master/closure/bin/build/depswriter.py#L125-L136

### PR DESCRIPTION
**Pull request by yamadayutaka**
### Resolves

#1159 

### Proposed Changes

Fixed to generate a dependency on a POSIX style path.

In "depswriter.py", the path is normalized by the following code.

https://github.com/google/closure-library/blob/master/closure/bin/build/depswriter.py#L125-L136

Fixed the test code so that the `npm run test` of ` closure-deps` completes successfully on Windows.

### CODE REVIEW

File: closure-deps/lib/normalize.js [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+  return pattern.replace(/\\/g, '\\\\');
+}
+
+/**
+ * Replaces OS-dependent path with POSIX style path.
+ * @param {string} p 
+ * @returns {string}
+ */
+exports.normalizePath = (p) => {
+  return p.replace(new RegExp(escapePattern(`^${path.resolve('/')}`)), path.posix.sep)
```
Comment (shicks) [inline closure-deps/lib/normalize.js:35]: This is a lot of nested parentheses, making it difficult to understand what's happening.  This could be clearer as

```
const root = new RegExp(...);
const nonPosixSep = new RegExp(...);
return p.replace(root, path.posix.sep).replace(nonPosixSep, path.posix.sep);
```
```

**Review by shicks — CHANGES_REQUESTED** [review]
Thanks for the PR - if you can address the two minor readability issues and (force) push a new rebased commit, we'll start the process of merging it internally.

File: closure-deps/lib/normalize.js [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+ * distributed under the License is distributed on an "AS-IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+const path = require('path');
+
+/**
+ * Escape regular expression pattern.
```
[the remark this answers is not in the document]
Comment (yamadayutaka) [reply closure-deps/lib/normalize.js]: I modified it as suggested.

File: closure-deps/lib/normalize.js (hunk 1 above)
Comment (yamadayutaka) [reply closure-deps/lib/normalize.js]: I changed it almost as suggested.
Only one point, the second regular expression matches the POSIX style separator on systems that use POSIX style paths, so I changed the variable name.

**Comment by yamadayutaka** [comment]
Thank you for reviewing my PR.
I pushed the modified code, so please check it.

**Review by shicks — APPROVED** [review]

**Comment by shicks** [comment]
Looks good, I'll try to get this merged.  I notice that GoogleBot has neither asked you to sign the CLA, nor tagged the PR with the CLA label.  Have you signed the CLA yet?  If not, please find the relevant info on another CL (e.g. #1146).

**Comment by yamadayutaka** [comment]
Thank you for confirmation.
I already signed the CLA when I contributed another project.

**Comment by yamadayutaka** [comment]
@googlebot  I signed it!
